name: tests

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [ '20.x', '22.x', '24.x' ]
        joi: [ '17', '18' ]
    name: test on node ${{ matrix.node }} with joi@${{ matrix.joi }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm ci
      - name: Install Joi matrix version
        run: npm i --no-save joi@${{ matrix.joi }}
      - name: Unit tests
        run: npm run test:unit:once
      - name: API tests
        run: npm run test:api:once
      - name: Coveralls (unit tests)
        if: matrix.node == '22.x' && matrix.joi == '18'
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
